/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

import yapl.impl.BackendMJ;
import yapl.lib.Type;

public
class ASTLiteral extends SimpleNode {

    private int value;

    private Type type;

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
        this.type = Type.INT;
    }

    public void setValue(boolean value) {
        this.value = (new BackendMJ()).boolValue(value);
    }

    public Type getType() {
        return type;
    }

    public ASTLiteral(int id) {
        super(id);
    }

    public ASTLiteral(Yapl p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=6d91aea268b46698b8b917f97ec7cee3 (do not edit this line) */
